### PR TITLE
Convert Articulate.Analytics.NET to netstandard2.0

### PR DESCRIPTION
**Pull request by rjacobw**
## Change Description

This change converts Articulate.Analytics.NET to `netstandard2.0`. Please take a close look to make sure I didn't mess anything up - particularly with the nuspec stuff. 

I did make sure that this package references the same version of Newtonsoft.Json (`13.0.1`) that the rest of our projects reference even though it's not the latest version. 

## Testing

I ran the unit tests locally and everything passed. Also, I left the test project at .Net Framework 4.8 just to make sure it could still load `Articulate.Analytics.NET.dll` without any issue since the rest of our projects are currently at 4.8.

## Reviewer Checklist

- [ ] Pull down the branch and build the code locally
- [ ] Review the testing steps described by the author above
- [ ] Repeat the author's testing efforts and consider any additional testing that might be useful
- [ ] Leave review comments about any code you don't understand or that could be improved
- [ ] When approving the PR, describe the testing that you did in the approval comment along with any additional testing that you feel should be performed by QA

### CODE REVIEW

**Comment by akindle** [comment]
the package produced by this looks fine, but i also opened #5 for your consideration

**Comment by rjacobw** [comment]
@akindle I merged your changes into my branch, made a few small updates, and am now pretty sure this good to merge. Let me know if there's anything else you think I should change while I'm here.

**Review by akindle — APPROVED** [review]

**Comment by akindle** [comment]
Ooh actually we could multi target it for net6 and net8 while we're here and pick up hypothetical future perf improvements

**Comment by rjacobw** [comment]
> Ooh actually we could multi target it for net6 and net8 while we're here and pick up hypothetical future perf improvements

Now multi-targeting `netstandard2.0`, `net6.0`, and `net8.0`.

**Comment by akindle** [comment]
:shipit:

**Pull request merged**
